---
name: Check Templates

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel
      - 618_templates_action

jobs:
  templates:
    name: Check Templates
    uses: pharmaverse/admiralci/.github/workflows/check-templates.yml@618_templates_action
    #if: github.event_name == 'pull_request'
    with:
      r-version: "4.1"
