---
name: Check Templates

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  templates:
    name: Check Templates
    uses: pharmaverse/admiralci/.github/workflows/check-templates.yml@27_template_fail_on_warnings
    #if: github.event.review.state == 'approved'
    with:
      r-version: "4.0"
