---
name: Dependency Conformance Test

on:
  workflow_dispatch:

jobs:
  dependency-test:
    strategy:
      fail-fast: false
      matrix:
        test-strategy: ["min_cohort", "min_isolated", "release", "max"]
    uses: insightsengineering/r.pkg.template/.github/workflows/verdepcheck.yaml@main
    name: Dependency Conformance Test - ${{ matrix.test-strategy }}
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
      GCHAT_WEBHOOK: ${{ secrets.GCHAT_WEBHOOK }}
    with:
      strategy: ${{ matrix.test-strategy }}
      additional-env-vars: |
        PKG_SYSREQS_DRY_RUN=true
      extra-deps: |
        lme4 (>= 1.1-35)
